Repository NYPL/research-catalog, pull requests merged in 2023-12, with the labels that each got.

#54 SCC-3704 - Search Results Item Sorting
  __test__/fixtures/itemFixtures.ts
  pages/search/advanced.tsx
  src/models/Item.ts
  src/models/SearchResultsBib.ts
  src/models/modelTests/Item.test.ts
  src/types/itemTypes.ts
  src/utils/itemUtils.ts
  src/utils/utilsTests/itemUtils.ts
Labels: Ship It

#45 Scc 3279/item filter mobile
  __test__/fixtures/testAggregations.js
  __test__/pages/search/advancedSearchForm.test.tsx
  src/components/ItemFilters/FiltersContainer.tsx
  src/components/ItemFilters/ItemFilter.tsx
  styles/components/ItemFilters.module.scss
Labels: Ship It

#53 SCC-3899: Focus ring accessibility fix
  src/components/Layout/Layout.tsx
  src/components/RCLink/RCLink.tsx
  src/components/SubNav/SubNav.tsx
Labels: needs review, a11y

#59 SCC-3904: Advanced Search page A11y and VQA fixes
  __test__/pages/search/advancedSearchForm.test.tsx
  package-lock.json
  package.json
  pages/search/advanced.tsx
Labels: needs review

#50 SCC-3776 - Item Table Component
  .env.example
  ENVIRONMENTVARS.md
  __test__/fixtures/itemFixtures.ts
  __test__/fixtures/searchResultPhysicalItems.ts
  pages/search/index.tsx
  src/components/ItemFilters/FiltersContainer.tsx
  src/components/ItemFilters/ItemFilter.tsx
  src/components/ItemTable/ItemAvailability.test.tsx
  src/components/ItemTable/ItemAvailability.tsx
  src/components/ItemTable/ItemTable.tsx
  src/components/ItemTable/RequestButtons.test.tsx
  src/components/ItemTable/RequestButtons.tsx
  src/components/SearchResult/SearchResult.test.tsx
  src/components/SearchResult/SearchResult.tsx
  src/config/config.ts
  src/models/Item.ts
  src/models/ItemFilterData.ts
  src/models/ItemTableData.ts
  src/models/SearchResultsBib.ts
  src/models/modelTests/Item.test.ts
  src/types/itemTypes.ts
  src/types/pageTypes.ts
  src/types/searchTypes.ts
  src/utils/itemFilterUtils.ts
  src/utils/itemUtils.ts
  src/utils/utilsTests/itemFilterUtils.test.tsx
  src/utils/utilsTests/itemUtils.ts
Labels: Changes Requested
